apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: react-app-ci-cd-
spec:
  entrypoint: ci-cd-pipeline
  templates:
    - name: ci-cd-pipeline
      steps:
        - - name: clone-repo
            template: git-clone
        - - name: build-image
            template: docker-build
        - - name: run-tests
            template: run-tests
        - - name: push-image
            template: docker-push
        - - name: deploy-to-k8s
            template: deploy-k8s

    - name: git-clone
      container:
        image: alpine/git
        command:
          [
            "git",
            "clone",
            "https://github.com/qingzhang100/travel-list-ci-cd.git",
            "/src",
          ]

    - name: docker-build
      container:
        image: docker
        command:
          ["docker", "build", "-t", "qingzhang100/react-app:latest", "/src"]

    - name: run-tests
      container:
        image: node:14
        command: ["npm", "test"]
        workingDir: /src

    - name: docker-push
      container:
        image: docker
        command: ["docker", "push", "qingzhang100/react-app:latest"]

    - name: deploy-k8s
      container:
        image: kubectl
        command: ["kubectl", "apply", "-f", "/src/kubernetes/deployment.yaml"]
